### ISSUE TITLE
Move androidvideo plugin to gst-plugins-bad

### ISSUE THREAD

**Issue by sdroege** [EricssonResearch/openwebrtc-gst-plugins#23]
Just a tracker issue to remind us of doing that sooner or later. Upstream GStreamer bug report: https://bugzilla.gnome.org/show_bug.cgi?id=737786

**Comment by sdroege** [comment]
Started with that btw

**Comment by Forkest** [comment]
What is the end of the story?

**Comment by sdroege** [comment]
This: https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/tree/sys/androidmedia/gstahcsrc.c

See also the bug report in Bugzilla linked above. OWR is not making use of that camera source though and still uses its own.
