### ISSUE TITLE
videorepair doesn't properly detect broken video when using h264 with multiple slices

### ISSUE THREAD

**Issue by Rugvip** [EricssonResearch/openwebrtc-gst-plugins#31]
videorepair considers the video repaired once an intra for a single slice has been received. This can result in e.g. 3/4 of the video being broken if using 4 slices.

**Comment by superdump** [comment]
I think we should only use videorepair dropping packets until next intra with decoders that don't handle error concealment (well) and then only with decoders that don't handle intra requests well.
