### ISSUE TITLE
sctp elements don't get event/dataflow order right

### ISSUE THREAD

**Issue by sdroege** [EricssonResearch/openwebrtc-gst-plugins#37]
With test-data-channel test application:

(lt-test-data-channel:19162): GStreamer-WARNING **: gstpad.c:4188:gst_pad_push_data:<sctpenc_1:src> Got data flow before stream-start event
[and follow up errors from that one]

**Comment by sancane** [comment]
Hi Sebastian,
I've sent a pull request with a fix for that issue I've also been suffering:
https://github.com/EricssonResearch/openwebrtc-gst-plugins/pull/38
Have a look at it, I hope it fixes the problem.
Regards
